name: dragons
description: Dart package to manage {Feature} data and domain layers.
version: 0.0.1+1

environment:
   sdk: ">=2.12.0 <3.0.0"

dependencies:
  # Scope Packages
  errors:
    git:
      url: git://github.com/NoScopeDevs/errors
  network_manager:
    git:
      url: git://github.com/NoScopeDevs/network_manager

  dartz: ^0.9.2
  json_annotation:
  freezed_annotation:
  meta:
  path:
  dio:

dev_dependencies:
  # code generators
  build_runner:
  freezed:
  json_serializable:

  # testing
  mockito:
  test:

  # static analysis
  very_good_analysis: